[package]
name = "miden-mock"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = []
keywords = []
edition = "2021"
rust-version = "1.67"

[[bin]]
name = "mock"
path = "src/main.rs"
required-features = ["executable"]

[features]
serde = ["dep:serde", "crypto/serde"]
executable = ["serde"]

[dependencies]
assembly = { workspace = true }
clap = { version = "4.4" }
crypto = { workspace = true }
env_logger = { version = "0.10" }
hex = "0.4"
miden-lib = { path = "../miden-lib" }
miden-objects = { path = "../objects" , features = ["serde", "log", "testing"]}
miden-test-utils = { workspace = true }
postcard = { version = "1.0", features = [ "alloc" ] }
rand = { version = "0.8" }
rand_pcg = { version = "0.3", features = ["serde1"] }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
vm-core = { workspace = true }
