[package]
name = "miden-mock"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = []
keywords = []
edition = "2021"
rust-version = "1.67"

[dependencies]
clap = { version = "4.4" }
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8" }
rand_pcg = { version = "0.3", features = ["serde1"] }
miden-objects = { path = "../objects" , features = ["mock", "serde", "log"]}
crypto = { workspace = true }
postcard = { version = "1.0", features = [ "alloc" ] }
env_logger = { version = "0.10" }
hex = "0.4"
