[package]
authors.workspace      = true
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "bench-prover"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
# Workspace dependencies
miden-objects = { features = ["testing"], workspace = true }
miden-testing = { workspace = true }
miden-tx      = { workspace = true }

# Miden dependencies
vm-processor = { workspace = true }

# External dependencies
anyhow     = "1.0"
serde      = { features = ["derive"], version = "1.0" }
serde_json = "1.0"

[dev-dependencies]
criterion = { features = ["html_reports"], version = "0.6" }

[[bench]]
harness = false
name    = "benches"
path    = "benches/benchmarks.rs"
