[workspace]
release_always = true # Without the tracking PR, it would never trigger unless `true`.
changelog_update = false # For now we have our own changelog.
git_tag_name = "v{version}"

# `cargo-semver` breaks because of the `async` feature (by default it runs with `--all-features`).
# We will either remove the feature (as discussed) or need to add an ability to release-plz to pass flags to `cargo-semver`.
[[package]]
name = "miden-testing"
semver_check = false
