[package]
authors.workspace      = true
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "bench-note-checker"
publish                = false
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
# Workspace dependencies
miden-lib     = { workspace = true }
miden-objects = { features = ["testing"], workspace = true }
miden-testing = { workspace = true }
miden-tx      = { workspace = true }

# External dependencies
anyhow = { workspace = true }
serde  = { features = ["derive"], version = "1.0" }
tokio  = { features = ["macros", "rt"], version = "1.0" }

[dev-dependencies]
criterion  = { features = ["async_tokio", "html_reports"], version = "0.6" }
tokio-test = "0.4"

[[bench]]
harness = false
name    = "benches"
path    = "benches/benchmarks.rs"
