[package]
authors.workspace      = true
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "bench-note-checker"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[dependencies]
# Workspace dependencies
miden-objects = { features = ["testing"], workspace = true }
miden-testing = { workspace = true }
miden-tx      = { workspace = true }
miden-lib     = { workspace = true }

# External dependencies
anyhow     = "1.0"
tokio      = { version = "1.0", features = ["rt", "macros"] }
serde      = { features = ["derive"], version = "1.0" }
serde_json = "1.0"

[dev-dependencies]
criterion = { features = ["html_reports", "async_tokio"], version = "0.6" }
tokio-test = "0.4"

[[bench]]
harness = false
name    = "benchmarks"
path    = "benches/benchmarks.rs"
