[package]
name = "miden-objects"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = ["no-std"]
keywords = []
edition = "2021"
rust-version = "1.67"

[[bench]]
name = "account_seed"
harness = false

[lib]
bench = false

[features]
default = ["std"]
std = ["assembly/std", "crypto/std", "miden-core/std"]

[dependencies]
assembly = { package = "miden-assembly", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "frisitano-next-dev", default-features = false }
crypto = { package = "miden-crypto", git = "https://github.com/0xPolygonMiden/crypto", branch = "next", default-features = false }
hashbrown = { version = "0.13.2" }
miden-core = { package = "miden-core", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "frisitano-next-dev", default-features = false }
miden-processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "frisitano-next-dev", default-features = false }
miden-verifier = { package = "miden-verifier", git = "https://github.com/0xPolygonMiden/miden-vm", branch = "frisitano-next-dev", default-features = false }


[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
