[package]
name = "miden-objects"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = ["no-std"]
keywords = []
edition = "2021"
rust-version = "1.67"

[[bench]]
name = "account_seed"
harness = false

[lib]
bench = false

[features]
default = ["std"]
std = ["assembly/std", "crypto/std", "vm-core/std", "vm-processor/std", "miden-verifier/std"]
testing = []
serde = ["dep:serde", "crypto/serde"]
concurrent = ["std"]

[dependencies]
assembly = { workspace = true }
crypto = { workspace = true }
log = { version = "0.4", optional = true }
miden-verifier = { workspace = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
vm-core = { workspace = true }
vm-processor = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"], default-features = false }
