[package]
name = "miden-objects"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = ["no-std"]
keywords = []
edition = "2021"
rust-version = "1.65"

[[bench]]
name = "account_seed"
harness = false

[lib]
bench = false

[features]
default = ["std"]
std = ["assembly/std", "crypto/std", "miden-core/std"]

[dependencies]
assembly = {  package = "miden-assembly", version = "0.4", default-features = false }
crypto = { package = "miden-crypto", version = "0.1", default-features = false }
miden-core = {  package = "miden-core",  version = "0.4", default-features = false }
miden-verifier = { package = "miden-verifier",  version = "0.4", default-features = false }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }