[package]
name = "miden-objects"
version = "0.1.0"
description = "Core components of the Miden rollup"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
categories = ["no-std"]
keywords = []
edition = "2021"
rust-version = "1.67"

[[bench]]
name = "account_seed"
harness = false

[lib]
bench = false

[features]
default = ["std"]
std = ["assembly/std", "crypto/std", "miden-core/std", "miden-lib/std", "miden-processor/std", "miden-verifier/std"]
testing = ["rand",  "winter-utils"]

[dependencies]
assembly = { package = "miden-assembly", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "frisitano-tx-result", default-features = false }
crypto = { package = "miden-crypto", git = "https://github.com/0xPolygonMiden/crypto.git", branch = "frisitano-from-merkle-store-trait", default-features = false }
miden-core = { package = "miden-core", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "frisitano-tx-result", default-features = false }
miden-lib = { path = "../miden-lib", default-features = false }
miden-processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "frisitano-tx-result", default-features = false }
miden-stdlib = { package = "miden-stdlib", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "frisitano-tx-result", default-features = false }
miden-verifier = { package = "miden-verifier", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "frisitano-tx-result", default-features = false }
winter-utils = { package = "winter-utils", optional = true, version = "0.6" }
rand = {version = "0.8.5", optional = true, features = ["std_rng"], default-features = false}

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
winter-utils = { package = "winter-utils", version = "0.6" }
miden-processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm.git", branch = "frisitano-tx-result", features = ["internals"]}
rand = {version = "0.8.5", features = ["std_rng"], default-features = false}
