// This file is generated by build.rs, do not modify

use crate::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 53] = [
    // account_get_initial_commitment
    word!("0xfd1d917f964b47e8649c55fb1faec452623fb378c7b658520daf910fcbbc90ca"),
    // account_compute_commitment
    word!("0xd6ca0cda7b20c7c61136f6db2ba1bbb0b62be010916782d73c75de13354b02c7"),
    // account_get_id
    word!("0xde8204c936d535388b4fd8910426d0b6a5be3959a8cdc1eab3da4e0daf406055"),
    // account_get_nonce
    word!("0x2cc91cdb158ce7bc124f72c8295986db88e944f18625f9e7170f657560080c96"),
    // account_incr_nonce
    word!("0x2c00882e1c45e11a57d20921473c008b014cc9ecd4eb3c81fcd0d99f147aa87f"),
    // account_get_code_commitment
    word!("0x70c5690b36f3b8aca01e16e07b6915b3c69ea9a8fdb5cf71a15ee18ba71b19b0"),
    // account_get_initial_storage_commitment
    word!("0xf7eabd578635c74cbd48cdbce9535a44b14a3bca420450d237a00cda18b93884"),
    // account_compute_storage_commitment
    word!("0xd209b3f1cd9bf777da372c85e4c8e821ea6afdd22ea31daf32558ef04758430c"),
    // account_get_item
    word!("0xa5fd21852ec10a80a18cd381b1cd602616c16006d4045a746ba0fd56db0fe799"),
    // account_get_initial_item
    word!("0x6a46761f27564207df3b6401d0e542583a978b31b44107e7f3834b5f7a5cd180"),
    // account_set_item
    word!("0x1966a28b7f7e5b917eec2ed58497cde67778d0454219f85d662dafa79c6f6087"),
    // account_get_map_item
    word!("0xd588ab7c3be830d043994a167125cc4ba679a33ebc1195c7a5e49d5a9cf88a22"),
    // account_get_initial_map_item
    word!("0xa5c3d909570e85b0d5612ec31ac15ee2f5fe810034c4395781e6d0ea4970b1d5"),
    // account_set_map_item
    word!("0x6c2f571dc2c075110c7de9d806db4d74b8f5f8753d42d6500bc9341133a2584e"),
    // account_get_initial_vault_root
    word!("0x72885bde7ca28257eaa00161a581d50e9d4746d09906db475f0c0b0d96524279"),
    // account_get_vault_root
    word!("0x7a4c90633b676fac3890da6c6eae6b44a4b29390484c2e8169baf26bb52a85db"),
    // account_add_asset
    word!("0x7620d82dcf26742ce856dfa4aab6f4c954ce3c9ea0719f26ee2d4dac0c88d2e5"),
    // account_remove_asset
    word!("0xdef0bf8dd5d4c8d5e4c3317ec801d82647b1ffd69dcaeb33d34e08ecf53f50ee"),
    // account_get_balance
    word!("0x1d7feff909f40a75d18ee5007621fd064df124ec8be590bc3a1942aa0a7e272a"),
    // account_get_initial_balance
    word!("0x2ec87700fa2e0cec0807cec7c4039b48e545e927b938ae5bf239543a30e1eb8d"),
    // account_has_non_fungible_asset
    word!("0x36141a5b136b44a7b62156981fcff4e5c523d766d86f145e238107497b31645a"),
    // account_compute_delta_commitment
    word!("0x65948a626d6cd4217ec9c5fc8601f86b1d815ac165b33dba67376e8d7587cf69"),
    // account_get_num_procedures
    word!("0x83a1ba98b8f57b0d1bf0b0772e1ea346748935eead6415386743bde854920e19"),
    // account_get_procedure_root
    word!("0x5f7acad9acebcacae3da8b6cecfa476cb736fd9866808265f441656ca3208122"),
    // account_was_procedure_called
    word!("0xc4e7fe7924b8388bd9a463226b9f6b5f78db787af9bb313094ca5f6d727ee6e6"),
    // account_has_procedure
    word!("0xef413aae054948109df0c01172f3ffb448ba51a96ed779b2f0f1ce841698b486"),
    // faucet_mint_asset
    word!("0x4efeca729279854b57e9c99c7da40fd3852920a053f6ae61e1af8fbbb692c0ea"),
    // faucet_burn_asset
    word!("0x92a63ae779ccc9816a657529c104412349f709a99df15fc82cff9b7f5ebaea21"),
    // faucet_get_total_fungible_asset_issuance
    word!("0x959a7cf7a6ed38e1a423a0e1af7fe6d04564c3e80ed86715dba4d2a594f20d78"),
    // faucet_is_non_fungible_asset_issued
    word!("0xfd81ed100deffd7eddd8f7ca294e14a03100d267ebc792845ddaa9963dd9e672"),
    // input_note_get_metadata
    word!("0x8e03a1e4a273d71df7f57ee201fce0b6aeccd5e8cf61790874328a302d68c2a8"),
    // input_note_get_assets_info
    word!("0xfb246bedcb535eb440051668a0c6f540728a7e1dbe5130b79b362f83e814f6df"),
    // input_note_get_script_root
    word!("0xb3dedc610f31081aab347a35ac29645e9bafd6ccf2b22d86f21c086eadd6ced0"),
    // input_note_get_storage_info
    word!("0x86367ce1f5f3575ecce188858f11a12cd8f03a16c5aa2b81c4b6c2175f841f0f"),
    // input_note_get_serial_number
    word!("0x03e77809318a875f1f2dfdcdb2d52f45d6202b5d3b9fcbad1eb31885edde6c1e"),
    // input_note_get_recipient
    word!("0x7da29887905e09af1e2743b00abe62bd8ea5705cfb4140587b66db94bc00c70f"),
    // output_note_create
    word!("0xf1240f8f4fa24f5baa6aa7817ce0d9a8a920b823fde01b42454f1db706814d00"),
    // output_note_get_metadata
    word!("0x94f0ecb903d086cdffc9b71b9543b1f31e60d20995963516bb113f9b6cfaaa76"),
    // output_note_get_assets_info
    word!("0xb9402aa2e4741721396b0eaed0b2edf8640b13c9a1d3430c686bb7794203bb25"),
    // output_note_get_recipient
    word!("0xa1a5e6f67b92f46df81d8b66df4ee36016539bc276978b4f2250525ed58eb722"),
    // output_note_add_asset
    word!("0xe274663f97ac7f395be448513d084f8d03a7af11e352942ec3ef938c74b2fdcd"),
    // output_note_set_attachment
    word!("0x8ce6990d8810de7be7abebe1b9bf489fc7373e52f6d10fbaf8f18dfb3243c3a9"),
    // tx_get_num_input_notes
    word!("0x60dca080ba4b4caa4c16ffa20bd75671a4326cf85f36e11df0b94eb45aa557a3"),
    // tx_get_input_notes_commitment
    word!("0xf0487f995534f6a0c37fb24a417477e2a06152915538a12eb590371c424c2acd"),
    // tx_get_num_output_notes
    word!("0x6ac521c8262639642c414125fc42dcee69265fec0bb530a29523c7a0f479341c"),
    // tx_get_output_notes_commitment
    word!("0xaf711405178619d52439900dc53216b1f205e8d1c214ad86ece969307d20efa8"),
    // tx_get_block_commitment
    word!("0x1bc70941599bbb5896cc34f53b9469f608543bda3bc63e59ee2efdf96ce6c992"),
    // tx_get_block_number
    word!("0x2e15ac5171985755455b725a76e6439280d382d771f582184a9e6e8d380a77fd"),
    // tx_get_block_timestamp
    word!("0x9c9e806229203ab4469c02e2aa9ba6d2290f738818de8e9cf260c8c1df636d6d"),
    // tx_start_foreign_context
    word!("0x5ce878c3871604ac5a9286661b161ac13687ad2189c20b0d3f985d6eeb42c799"),
    // tx_end_foreign_context
    word!("0xe008fa7cf5de756aef83253d76dc2292dc6d054cd382781053946e3f1761852f"),
    // tx_get_expiration_delta
    word!("0xef39565ca6be680d9fe8f4c5295b4650e2b09fc5caf12d76a5b77e8f8e472e99"),
    // tx_update_expiration_block_delta
    word!("0x39ceba52dbe0444fc9e63d8e70447b65e36c9d489f2e569ed3c5ef537d58bda8"),
];
