[package]
name = "miden-bench-tx"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[[bin]]
name = "bench-tx"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
miden-lib = { workspace = true }
miden-objects = { workspace = true }
miden-testing = { workspace = true }
miden-tx = { workspace = true, features = ["testing"] }

# Miden dependencies
vm-processor = { workspace = true }

# External dependencies
anyhow = { version = "1.0", features = ["std", "backtrace"] }
rand_chacha = { version = "0.9", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = { package = "serde_json", version = "1.0", features = ["preserve_order"] }

