[package]
authors.workspace      = true
edition.workspace      = true
exclude.workspace      = true
homepage.workspace     = true
license.workspace      = true
name                   = "miden-bench-tx"
repository.workspace   = true
rust-version.workspace = true
version                = "0.1.0"

[[bin]]
name = "bench-tx"
path = "src/main.rs"

[dependencies]
# Workspace dependencies
miden-lib     = { workspace = true }
miden-objects = { workspace = true }
miden-testing = { workspace = true }
miden-tx      = { features = ["testing"], workspace = true }

# Miden dependencies
miden-processor = { workspace = true }

# External dependencies
anyhow      = { features = ["backtrace", "std"], version = "1.0" }
rand_chacha = { default-features = false, version = "0.9" }
serde       = { features = ["derive"], version = "1.0" }
serde_json  = { features = ["preserve_order"], package = "serde_json", version = "1.0" }
