//! This file is generated by build.rs, do not modify

use miden_objects::{word, Word};

// KERNEL V0 PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed procedures from the kernel 0.
pub const KERNEL0_PROCEDURES: [Word; 48] = [
    // account_get_initial_commitment
    word!("0x920898348bacd6d98a399301eb308478fd32b32eab019a5a6ef7a6b44abb61f6"),
    // account_compute_current_commitment
    word!("0x1aed40e2cc4d3798448f4efdce1a14c9598611da065eebe58432f144c3bca9de"),
    // account_get_id
    word!("0xc9f7e71b294e16d7a297ba283afb2f8c864817e40e73b6ef1d64efc310937fc7"),
    // account_get_nonce
    word!("0x4a1f11db21ddb1f0ebf7c9fd244f896a95e99bb136008185da3e7d6aa85827a3"),
    // account_incr_nonce
    word!("0xa7c09f7f56e1b5ab83d66e1b2050d5a52f35bbff36458462e41a8ee3929cec90"),
    // account_get_code_commitment
    word!("0x0e0ab7cc8a078a44c3e7cbd55bb2c46e7b5efcaa6008ab3e9fe82b1232fb0097"),
    // account_get_initial_storage_commitment
    word!("0x5932cb0394cc85330e65e4c0325bb869ec1d08b295c310f7375076a98b143d57"),
    // account_compute_storage_commitment
    word!("0xf68a1502f295a0c0b4feb6e7df38e6d854adf0311f845bde45e2a6dd32e2df15"),
    // account_get_item
    word!("0x2497b281a67e09c45f64a1d8e977c2d7a35ae25f9c42c31b1d3b2e128ec43268"),
    // account_set_item
    word!("0x14fe1427ca3090bce84182053adef71fdee4943f9cbd461d8c6c661089ae312a"),
    // account_get_map_item
    word!("0xd88548ed6a70a427f6e1df90ac513e9e13693394f10efc73176a411355199907"),
    // account_set_map_item
    word!("0x9ec13eaba59f8ff9b8e6029c34392926b5aba72392a61e6dc85e732de0007d2e"),
    // account_get_initial_vault_root
    word!("0x4d4d91079aaacad1bc86b29a0d61d25508ccb705c29d1b1357016f7373bf299e"),
    // account_get_vault_root
    word!("0x42a2bfb8eac4fce9bbf75ea15215b00729faeeaf7fff784692948d3f618a9bb7"),
    // account_add_asset
    word!("0x965c8fac19222f5a3be341ecd35d5be63aee6254ac17d7fb463b9148ced4500c"),
    // account_remove_asset
    word!("0xf893ba17021bba937067ee6b1147dbf7f3e218e0ea1a6347ceae77d5a64532a4"),
    // account_get_balance
    word!("0x6da3117398e2aa2dd06f5020bd7aa7de5ba21dfc8df578ecad931176a4873432"),
    // account_has_non_fungible_asset
    word!("0xc3f97de70f82ab71b91acb846f39e2831ce23e2077c481b27dba2edbdd1e3f55"),
    // account_compute_delta_commitment
    word!("0x95dab713c8f9fe01a4c81d1fb57737ac6a45171659456dbc03df049654db3d78"),
    // account_was_procedure_called
    word!("0xdd79f77dec549280a4ae375dee30093244c10ec79bbf48f76eb53868f710b3a8"),
    // faucet_mint_asset
    word!("0xb2146f7a110123d14b04deadfcb29c30ab12df31d8ed1413c50295949f0af142"),
    // faucet_burn_asset
    word!("0x73829fd4e84684e68be209eaf40a5b7a9ecd3425cdc6419dedbed8fd10349030"),
    // faucet_get_total_fungible_asset_issuance
    word!("0x7d32952d4dc0edd0311e3424b8128df2d48cf949f800c28218fbc851a8db42b5"),
    // faucet_is_non_fungible_asset_issued
    word!("0x1f73da53fbeaae2a1dbeb1d84e6b115460cbc4c6a0dfeb62c123c40b5f2d4a5e"),
    // note_get_assets_info
    word!("0x13a1496a239fa95b3b376c53d899ce2d495e956cdae0f121666408462784673a"),
    // note_add_asset
    word!("0xea700d2a3697131e1899c467c295f19f7bb77345f58b2d01f6b78313b69bf9c0"),
    // note_get_serial_number
    word!("0x6989241a99d9aa1630daae03fc55ecac269e184d6b455c7c0bc996d15ef7f9a8"),
    // note_get_inputs_commitment_and_len
    word!("0x6ae9f25739a4368330c40e9bd21e5beed4583656443877f3f59cad5040decee1"),
    // note_get_sender
    word!("0x125832eac0e511f2d86c508b5fa79b7ea6a302c4200222c7f58e1832260bde8f"),
    // note_get_script_root
    word!("0x317c3f724d57093c98927f7820dc00f5cf3509d2de4306dccaef4e2266fcd5b6"),
    // input_note_get_assets_info
    word!("0x0816c7215676487f3ce03d372bf5512afb528ab62466074921829d7d2974147c"),
    // output_note_get_assets_info
    word!("0xb049eba122c84d64780a0cd177eae9738a8fdbd0fe613d0965910ba6a8757984"),
    // input_note_get_recipient
    word!("0x1e612cf8aa3cca674363d9e1fb15c666a0cf2febc80bf9d7800920941133a3f4"),
    // output_note_get_recipient
    word!("0xc824115ed79a2e1670daed8c18fba1bc15f54c5ec0ec6699de69a00b21d9df92"),
    // input_note_get_metadata
    word!("0x4b0c2a8560a007abadd55013c3b3c620b2de2189c08109500ba46a4222b37d89"),
    // output_note_get_metadata
    word!("0xde4a5b57f9d53692459383e6cf6302ef3602a348896ed6ab6fdf67e07fa483ff"),
    // tx_create_note
    word!("0xed3245c2ad375348eb7b7b8f900c47032369841ec655a4d3dd523a61ebd7f593"),
    // tx_get_input_notes_commitment
    word!("0xc3a334434daa7d4ea15e1b2cb1a8000ad757f9348560a7246336662b77b0d89a"),
    // tx_get_num_input_notes
    word!("0xfcc186d4b65c584f3126dda1460b01eef977efd76f9e36f972554af28e33c685"),
    // tx_get_output_notes_commitment
    word!("0xd5b22dae48ec4b20ed479f2c43573d34930720886371ef6b484310a3bea4e818"),
    // tx_get_num_output_notes
    word!("0x2511fca9c078cd96e526fd488d1362cbfd597eb3db8452aedb00beffee9782b4"),
    // tx_get_block_commitment
    word!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    word!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    word!("0x7903185b847517debb6c2072364e3e757b99ee623e97c2bd0a4661316c5c5418"),
    // tx_start_foreign_context
    word!("0x6ea6ee447aa40b81a821f4387a83666c537f9d57900c6de7b401f3e7f91af9ec"),
    // tx_end_foreign_context
    word!("0xaa0018aa8da890b73511879487f65553753fb7df22de380dd84c11e6f77eec6f"),
    // tx_get_expiration_delta
    word!("0xa60286e820a755128b2269db5057b0e2d9b79fef6f813bf3fe3337553a8fbb53"),
    // tx_update_expiration_block_num
    word!("0xa16440a9a8cd2a6d0ff7f5c3bcce2958976e5d3e6e8a6935ff40ae1863c324f0"),
];
