//! This file is generated by build.rs, do not modify

use miden_objects::{digest, Digest};

// KERNEL V0 PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed procedures from the kernel 0.
pub const KERNEL0_PROCEDURES: [Digest; 37] = [
    // account_get_initial_commitment
    digest!("0x920898348bacd6d98a399301eb308478fd32b32eab019a5a6ef7a6b44abb61f6"),
    // account_get_current_commitment
    digest!("0x1c294b4d92eedce11252353164d712200adfa5cc443ac3667dd86ef33b303c8c"),
    // account_get_id
    digest!("0x1a5583b3a4011d0ca83ac9633fc12b0c6ec2cba03ee8c5f380ac69fc4f767075"),
    // account_get_nonce
    digest!("0xf1dfe3621b9147803b6668352915be7fb7f85df476c9d18052272270a854fa75"),
    // account_incr_nonce
    digest!("0xecdd4bd7bb0f2e93c6b927d85b952d913d815aa1899ed312345b4d7ca8c10d34"),
    // account_get_code_commitment
    digest!("0xed9425332a9d92654095a73ce6de35cefc5dfaeb366bb97ce2752e7de6664913"),
    // account_get_storage_commitment
    digest!("0x156617f3468741dbe70476d1bee422e972db2fd726d61ff57cc01ced6119fd0d"),
    // account_get_item
    digest!("0x9cf8a4fb028bfa7fe93167c1638f652dbc69fda8abc45b35a45950e9d254fdac"),
    // account_set_item
    digest!("0x4839791daa3c095a4b7e727ada7782b5e91166ac1ad9dcede44c2ce278adb97a"),
    // account_get_map_item
    digest!("0xd48d709c63d15de3e8a6f9860045c7a940ef0055482b79a812f5e3c9b5e2c852"),
    // account_set_map_item
    digest!("0x52a82f3d9aed2f0d0ac63f074154b943b26d70c1e1ca60af59d3561d95b89952"),
    // account_get_vault_root
    digest!("0x279b4a9e5adca07f01cadf8ecc1303fa3c670003a7a4e69f09506b070c4023df"),
    // account_add_asset
    digest!("0x0e7d26f9cf938cc6fa2e84cfeb54d5ca9f6e923117dcdcb350e1b030c712b644"),
    // account_remove_asset
    digest!("0x7033425d6253f7e5e350f1871ea9b4cf6286b84138f4c8a382ce1b9d276e91d8"),
    // account_get_balance
    digest!("0xc3385953bc66def5211f53a3c44de8facfb4060abbb1c9708859c314268989e8"),
    // account_has_non_fungible_asset
    digest!("0x4fea67ed25474d5494a23c5e1e06a93f8aa140d0a673c6e140e0d4f1dd8bd835"),
    // account_was_procedure_called
    digest!("0xedcb9151a8f56a5681e473b40356136c5808bfef324d83b2641f6cf4becdc6f5"),
    // faucet_mint_asset
    digest!("0xc40e52b7d610c1832f1d5a1fa15903902ddb142241206713e37ca63ace80a646"),
    // faucet_burn_asset
    digest!("0xc6d3ffd5c2bf092a85e5c0064b2e5ff2f25492352d2b29b38e43e8a844f7c659"),
    // faucet_get_total_fungible_asset_issuance
    digest!("0xd2ee4bd330f989165ee2be0f121a4db916f95e58f6fd2d040d57672f2f0cef63"),
    // faucet_is_non_fungible_asset_issued
    digest!("0xdeb06f05d996cf844d3ab04ad6aacc373b11fc1b7e0907a44bd01ad201339867"),
    // note_get_assets_info
    digest!("0x8a1a66c95fd9dd85e47e30d9ba64be7803dcb7d03f612235722cc484ea865b3f"),
    // note_add_asset
    digest!("0xb9e001fcd473132abf7b2a650516cfeb7bafdb95da326824656a3d439995a537"),
    // note_get_serial_number
    digest!("0x59b3ea650232049bb333867841012c3694bd557fa199cd65655c0006edccc3ab"),
    // note_get_inputs_commitment_and_len
    digest!("0x8597b07c458fe3b3cdab1a2a01ca05476501442f3c559c2de7080403bb4398fd"),
    // note_get_sender
    digest!("0x01172024b89517e5da80121cedfa6c19dd2ace0fe4d09a8cde6605103fe62952"),
    // note_get_script_root
    digest!("0x66fb188ca538d9f8bc6fd1aedbd19336bf6e3a1c0ae67b5f725cbc9cb4f7867f"),
    // tx_create_note
    digest!("0x49bf09e20abf6f2d4aa48b7200614633d61cec0d9c128a4dee0a0c1f102d080d"),
    // tx_get_input_notes_commitment
    digest!("0x16cb840dc9131e2fd2b3e83b8d796eb466722ae36f29f27b4b053f1bee2ed473"),
    // tx_get_output_notes_commitment
    digest!("0x0c241940512d130ad36c70c4e946285cb5841f2655c4fe12df001cb834256a29"),
    // tx_get_block_commitment
    digest!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    digest!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    digest!("0x786863e6dbcd5026619afd3831b7dcbf824cda54950b0e0724ebf9d9370ec723"),
    // tx_start_foreign_context
    digest!("0x50e31990bc918903f0babea20d4eb840828fdd41b539adb98f70cde6fffa8bfc"),
    // tx_end_foreign_context
    digest!("0x90a107168d81c1c0c23890e61fb7910a64b4711afd0bf8c3098d74737e4853ba"),
    // tx_get_expiration_delta
    digest!("0x756352beed1624a42d4540c434a4faa986d6d9d08ef8437699d9086fcd9ad9e7"),
    // tx_update_expiration_block_num
    digest!("0x11ca0c8662d20e6b05fbff4a20423bfa52595862b6c7c5c5ef1cc0a917e4cb62"),
];
