//! This file is generated by build.rs, do not modify

use miden_objects::{digest, Digest};

// KERNEL V0 PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed procedures from the kernel 0.
pub const KERNEL0_PROCEDURES: [Digest; 37] = [
    // account_get_initial_commitment
    digest!("0x920898348bacd6d98a399301eb308478fd32b32eab019a5a6ef7a6b44abb61f6"),
    // account_get_current_commitment
    digest!("0x1c294b4d92eedce11252353164d712200adfa5cc443ac3667dd86ef33b303c8c"),
    // account_get_id
    digest!("0x1a5583b3a4011d0ca83ac9633fc12b0c6ec2cba03ee8c5f380ac69fc4f767075"),
    // account_get_nonce
    digest!("0xf1dfe3621b9147803b6668352915be7fb7f85df476c9d18052272270a854fa75"),
    // account_incr_nonce
    digest!("0xf47994fd1d768328fb1a1717f2101b84e627578abc7bc9cdb3eecc2147cc456c"),
    // account_get_code_commitment
    digest!("0x807a4183a40b2e65b8e04f9e8d13f12b5372b4a7a2910b1209cf67ccbb3d6e20"),
    // account_get_storage_commitment
    digest!("0x9d64c7525b4abf37fc50e4203a0f7cffc757a031719932230a169b21a5a68a21"),
    // account_get_item
    digest!("0x2769600f71d8a38441f7bb7f6e877a307eb8d3290494fbc1b978124e2b240e6d"),
    // account_set_item
    digest!("0xefb681fb07ca3f7972b2a4196f59ba64c121ef257e22c9348feaa2235459608a"),
    // account_get_map_item
    digest!("0x9c8c8586252de23b4e9d75e5591dec26025c61afa946628a28c8d4646dd8aaa9"),
    // account_set_map_item
    digest!("0xd9e8fb82e9eef51047748804c1e73e0637045297b4f9f9ace311930fdd532b77"),
    // account_get_vault_root
    digest!("0x279b4a9e5adca07f01cadf8ecc1303fa3c670003a7a4e69f09506b070c4023df"),
    // account_add_asset
    digest!("0xba139da68ea04f1e4259943fd8bb9a8692e03a2bb152d52ff1cf64fe70448373"),
    // account_remove_asset
    digest!("0x8d33ef93b3c82388c34d5a97a0db1a53b3deead4257c06105d3e1a1e92a29e62"),
    // account_get_balance
    digest!("0xc3385953bc66def5211f53a3c44de8facfb4060abbb1c9708859c314268989e8"),
    // account_has_non_fungible_asset
    digest!("0x4fea67ed25474d5494a23c5e1e06a93f8aa140d0a673c6e140e0d4f1dd8bd835"),
    // account_was_procedure_called
    digest!("0xb1e12cb3e2eeb3c940e9465845e93fe2c799ecf5f7c2b468e7fff9d26fd57f4b"),
    // faucet_mint_asset
    digest!("0x10a0b3809e8134e0692678b440c2293ca61fa3806927c0ed7bb9c928b90c3082"),
    // faucet_burn_asset
    digest!("0xb8e24d03edbea8ef206106b4f7ad7881373c3267923439fbb3f9dcf5079d8241"),
    // faucet_get_total_fungible_asset_issuance
    digest!("0xd2ee4bd330f989165ee2be0f121a4db916f95e58f6fd2d040d57672f2f0cef63"),
    // faucet_is_non_fungible_asset_issued
    digest!("0xdeb06f05d996cf844d3ab04ad6aacc373b11fc1b7e0907a44bd01ad201339867"),
    // note_get_assets_info
    digest!("0x8a1a66c95fd9dd85e47e30d9ba64be7803dcb7d03f612235722cc484ea865b3f"),
    // note_add_asset
    digest!("0x3b70f146d724c11e3510f596e11a1736b37853aac4b25b4b955db6d777ccf79d"),
    // note_get_serial_number
    digest!("0x59b3ea650232049bb333867841012c3694bd557fa199cd65655c0006edccc3ab"),
    // note_get_inputs_commitment_and_len
    digest!("0x8597b07c458fe3b3cdab1a2a01ca05476501442f3c559c2de7080403bb4398fd"),
    // note_get_sender
    digest!("0x01172024b89517e5da80121cedfa6c19dd2ace0fe4d09a8cde6605103fe62952"),
    // note_get_script_root
    digest!("0x66fb188ca538d9f8bc6fd1aedbd19336bf6e3a1c0ae67b5f725cbc9cb4f7867f"),
    // tx_create_note
    digest!("0x68fe140321a9ef6bd23a2bf7a86c4a6914e922f3402c4d78155bf582c43702d7"),
    // tx_get_input_notes_commitment
    digest!("0x16cb840dc9131e2fd2b3e83b8d796eb466722ae36f29f27b4b053f1bee2ed473"),
    // tx_get_output_notes_commitment
    digest!("0x0c241940512d130ad36c70c4e946285cb5841f2655c4fe12df001cb834256a29"),
    // tx_get_block_commitment
    digest!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    digest!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    digest!("0x786863e6dbcd5026619afd3831b7dcbf824cda54950b0e0724ebf9d9370ec723"),
    // tx_start_foreign_context
    digest!("0x50e31990bc918903f0babea20d4eb840828fdd41b539adb98f70cde6fffa8bfc"),
    // tx_end_foreign_context
    digest!("0x90a107168d81c1c0c23890e61fb7910a64b4711afd0bf8c3098d74737e4853ba"),
    // tx_get_expiration_delta
    digest!("0x756352beed1624a42d4540c434a4faa986d6d9d08ef8437699d9086fcd9ad9e7"),
    // tx_update_expiration_block_num
    digest!("0x11ca0c8662d20e6b05fbff4a20423bfa52595862b6c7c5c5ef1cc0a917e4cb62"),
];
