[package]
name = "miden-tx-prover"
version = "0.6.0"
description = "Miden rollup transaction prover"
readme = "README.md"
keywords = ["miden", "transaction"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "prover-service"
path = "src/main.rs"
required-features = ["std"]

[lib]
crate-type = ["lib"]

[features]
default = ["std"]
std = ["miden-objects/std", "miden-tx/std", "dep:tokio", "dep:tonic-web", "dep:tokio-stream", "dep:axum",  "dep:tracing", "dep:tracing-subscriber", "tonic/transport"]
async = ["miden-tx/async"]
wasm-transport = ["async", "dep:tonic-web-wasm-client", "dep:getrandom"]

[dependencies]
async-trait = "0.1"
axum = {version = "0.7", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }
miden-lib = { workspace = true, default-features = false }
miden-objects = { workspace = true, default-features = false }
miden-tx = { workspace = true, default-features = false }
prost = { version = "0.13", default-features = false, features = ["derive"] }
tokio = { version = "1.38", optional = true, features = ["full"] }
tokio-stream = { version = "0.1", optional = true, features = [ "net" ]}
tonic = { version = "0.12", default-features = false, features = ["prost", "codegen"] }
tonic-web = { version = "0.12", optional = true }
tonic-web-wasm-client = { version = "0.6", optional = true, default-features = false }
tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.3", features = ["fmt",  "json",  "env-filter"], optional = true }
winter-maybe-async = { version = "0.10" }

[dev-dependencies]
miden-lib = { workspace = true , default-features = false, features = ["testing"]}
miden-objects = { workspace = true, default-features = false, features = ["testing"] }
miden-tx = { workspace = true, default-features = false, features = ["testing"] }

[build-dependencies]
miette = { version = "7.2", features = ["fancy"] }
prost = { version = "0.13", default-features = false, features = ["derive"] }
prost-build = { version = "0.13" }
protox = { version = "0.7" }
tonic-build = { version = "0.12" }
