[profile.default]
fail-fast      = false
failure-output = "immediate-final"

[profile.prove]
# A test which also generates a proof takes around 120sec to complete in the CI
fail-fast      = false
failure-output = "immediate-final"
slow-timeout   = { period = "200s", terminate-after = 2 }
