[book]
title = "The Miden protocol"
authors = ["Miden team"]
description = "Description and core structures for the Miden rollup protocol"
multilingual = false
language = "en"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-base"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
