[book]
authors      = ["Miden team"]
description  = "Description and core structures for the Miden rollup protocol"
language     = "en"
multilingual = false
title        = "The Miden Protocol"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/miden-node"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
