site_name: Polygon Knowledge Layer

nav:
  - Miden: index.md
  - Overview: overview.md
  - Roadmap:  roadmap.md
  - Getting started: getting-started.md
  - Architecture:
      - Overview:  architecture/overview.md
      - Accounts:  architecture/accounts.md
      - Notes:  architecture/notes.md
      - Assets: architecture/assets.md
      - Transactions:  
          - Transaction execution: architecture/transaction-execution.md
          - Transaction kernel: architecture/transaction-kernel.md
          - Transaction procedures: architecture/transaction-procedures.md
          - Transaction modes: architecture/transaction-modes.md
      - State:  architecture/state.md
      - Batching and blocks:
          - Batching and recursion: architecture/batching-recursion.md
          - Block kernel: architecture/block-kernel.md
      - Network:
          - Bridge: architecture/bridge.md
          - Deposit: architecture/deposit.md

