site_name: Polygon Knowledge Layer

nav:
    - Miden: miden/index.md
    - Overview: miden/overview.md
    - Roadmap:  miden/roadmap.md
    - Miden rollup docs:
        - Introduction:  
            - Welcome: miden/introduction/index.md
        - Architecture:
            - Architecture:  miden/architecture/index.md
            - Accounts:  miden/architecture/accounts.md
            - Notes:  miden/architecture/notes.md
            - Assets:  miden/architecture/assets.md
            - Transactions:  miden/architecture/transactions.md
            - State:  miden/architecture/state.md
            - Execution:  miden/architecture/execution.md
        - Concepts:
            - Crypto primitives:
                - Tiered sparce Merkle tree (TSMT):  miden/concepts/crypto-primitives/tsmt.md

