use miden_protocol::errors::MasmError;

// This file is generated by build.rs, do not modify manually.
// It is generated by extracting errors from the MASM files in the `./asm` directory.
//
// To add a new error, define a constant in MASM of the pattern `const ERR_<CATEGORY>_...`.
// Try to fit the error into a pre-existing category if possible (e.g. Account, Note, ...).

// AGGLAYER ERRORS
// ================================================================================================

/// Error Message: "first 4 bytes (addr0) must be zero"
pub const ERR_ADDR0_NONZERO: MasmError = MasmError::from_static_str("first 4 bytes (addr0) must be zero");

/// Error Message: "B2AGG script requires exactly 1 note asset"
pub const ERR_B2AGG_WRONG_NUMBER_OF_ASSETS: MasmError = MasmError::from_static_str("B2AGG script requires exactly 1 note asset");
/// Error Message: "B2AGG script expects exactly 6 note inputs"
pub const ERR_B2AGG_WRONG_NUMBER_OF_INPUTS: MasmError = MasmError::from_static_str("B2AGG script expects exactly 6 note inputs");

/// Error Message: "CLAIM's target account address and transaction address do not match"
pub const ERR_CLAIM_TARGET_ACCT_MISMATCH: MasmError = MasmError::from_static_str("CLAIM's target account address and transaction address do not match");

/// Error Message: "invalid claim proof"
pub const ERR_INVALID_CLAIM_PROOF: MasmError = MasmError::from_static_str("invalid claim proof");

/// Error Message: "address limb is not u32"
pub const ERR_NOT_U32: MasmError = MasmError::from_static_str("address limb is not u32");

/// Error Message: "prefix would wrap field modulus"
pub const ERR_PREFIX_OUT_OF_FIELD: MasmError = MasmError::from_static_str("prefix would wrap field modulus");

/// Error Message: "maximum scaling factor is 18"
pub const ERR_SCALE_AMOUNT_EXCEEDED_LIMIT: MasmError = MasmError::from_static_str("maximum scaling factor is 18");

/// Error Message: "suffix would wrap field modulus"
pub const ERR_SUFFIX_OUT_OF_FIELD: MasmError = MasmError::from_static_str("suffix would wrap field modulus");
