// This file is generated by build.rs, do not modify

use miden_objects::{Word, word};

// KERNEL PROCEDURES
// ================================================================================================

/// Hashes of all dynamically executed kernel procedures.
pub const KERNEL_PROCEDURES: [Word; 52] = [
    // account_get_initial_commitment
    word!("0x1bbebdc5b04407925b05dee65911648144a4736cc29bf5156121d9f9845ca552"),
    // account_compute_commitment
    word!("0x1be7cd026a891235ab0401c2f1d3ab162583375ee4b5b9c301c8197a9334ab30"),
    // account_get_id
    word!("0xd76288f2e94b9e6a8f7eeee45c4ee0a23997d78496f6132e3f55681efea809c4"),
    // account_get_nonce
    word!("0x4a1f11db21ddb1f0ebf7c9fd244f896a95e99bb136008185da3e7d6aa85827a3"),
    // account_incr_nonce
    word!("0xd1316d21f95e20385283ac72914585a4a3281ff69935540d130fd1ace25ec9ae"),
    // account_get_code_commitment
    word!("0x8c044d53df35c71425c806b8997c6541e0aac70d7880657e9354b9854626ce3e"),
    // account_get_initial_storage_commitment
    word!("0x91377c2852feb7a2798e54d7dbaa2d97000270ec4c0d0888b26d720a25ae0e84"),
    // account_compute_storage_commitment
    word!("0x3a23d1218e58884afe87df989f56f923fe5cec6875587a7d3190b1d6a530d3fd"),
    // account_get_item
    word!("0x0b001ad75998639c9b7e212696b851ed25bb750a309b51809ff44735ef45e848"),
    // account_get_initial_item
    word!("0xcef7817dc0618f198f7fd2eb30e4595e51d56947af26c4bcb667184f8dbc6e9a"),
    // account_set_item
    word!("0x9a814c196233497b14726c6d0f0e44ddd371c8eeb8e37131b5c0fef28cf9e177"),
    // account_get_map_item
    word!("0x031295794f6b94f17b4fd33084cb6bcb1afdd3075b78cc33ad49410b93f4e168"),
    // account_get_initial_map_item
    word!("0xfb8800511ba276a0b148cb069bb2e9ef5595c00b57d5452c9df57c749c60f224"),
    // account_set_map_item
    word!("0xb43811f4773414f6d0e7ac8567f71877579d36a86a4eb682a7e5674798f3c042"),
    // account_get_initial_vault_root
    word!("0x46297d9ac95afd60c7ef1a065e024ad49aa4c019f6b3924191905449b244d4ec"),
    // account_get_vault_root
    word!("0x42a2bfb8eac4fce9bbf75ea15215b00729faeeaf7fff784692948d3f618a9bb7"),
    // account_add_asset
    word!("0x75e527cd32297a838f8e47af2f2f69d2c14eb03b9ab9554d98c8caa6e3b3f049"),
    // account_remove_asset
    word!("0xf4df1ee5eaa4effe8e6dcacf701a73a72f2dfc406dc8e193fe480f68b185f5bd"),
    // account_get_balance
    word!("0x1ed792cc7775aa1ce2f32367a3d430561ec9bceb33f5bb222691c49a6bde8112"),
    // account_get_initial_balance
    word!("0xdc1320d6f044c40d37e5e835a584b643d6e77e3fc1136f498815298e28c912b8"),
    // account_has_non_fungible_asset
    word!("0xfaad11de0c026551df15231790c2364cc598e891444bf826da01b524b1a8ca8f"),
    // account_compute_delta_commitment
    word!("0x0d791c9be955c547160a13ec6dabb88e24d89dc2d201062cedc2c42713d2c581"),
    // account_get_num_procedures
    word!("0x53b5ec38b7841948762c258010e6e07ad93963bcaac2d83813f8edb6710dc720"),
    // account_get_procedure_root
    word!("0xa45796077477599813ea54d88a83dfca3e64b1c112117970d63a1c24f7cfef5a"),
    // account_was_procedure_called
    word!("0xd9e08c27f3f1e7d01d257cbb4583ecf14f5e362d9c19e39ada8bc19dcc820d45"),
    // account_has_procedure
    word!("0xb0b63fdd01af0bcb4aacb2412e934cdc7691308647152d416c7ae4fc909da076"),
    // faucet_mint_asset
    word!("0x2f678d04d34d9c5fa3999f8afe67b90541d283145ce6b126339ef0829b5e5c52"),
    // faucet_burn_asset
    word!("0xfd3ee96700d65ee217eae73259c8eeb4bd3e5a18e71afbc4230a64a067eae8a1"),
    // faucet_get_total_fungible_asset_issuance
    word!("0x8b7e6fe35aad099792f7aed7bf49437d5fc91ba086f6ee192c2f62b645e97c28"),
    // faucet_is_non_fungible_asset_issued
    word!("0x1a7d7f5ade931849e6f3a2307237393f36730b25bf5afbe0d42d607a8700e1b8"),
    // input_note_get_metadata
    word!("0x7ad3e94585e7a397ee27443c98b376ed8d4ba762122af6413fde9314c00a6219"),
    // input_note_get_assets_info
    word!("0x159439fe48dbc11e674c5d05830d0408dcfa033c26e85e01256002c6cbc07e9a"),
    // input_note_get_script_root
    word!("0x527036257e58c3a84cf0aa170fb3f219a4553db17d269279355ad164a2b90ac5"),
    // input_note_get_inputs_info
    word!("0xdd8bbf4cdb48051da346bc89760b77fdf4c948904276a99d96409922a00bd322"),
    // input_note_get_serial_number
    word!("0x25815e02b7976d8e5c297dde60d372cc142c81f702f424ac0920190528c547ee"),
    // input_note_get_recipient
    word!("0xd3c255177f9243bb1a523a87615bbe76dd5a3605fcae87eb9d3a626d4ecce33c"),
    // output_note_create
    word!("0x6562a9d1d8605d158415a4dcd4c8fd48fc2b6c21ec64c188db9def16b991a560"),
    // output_note_get_metadata
    word!("0xde4a5b57f9d53692459383e6cf6302ef3602a348896ed6ab6fdf67e07fa483ff"),
    // output_note_get_assets_info
    word!("0x7e5d726b5f25f6cfd533bd0294853f3fceea62c41e5f2fd68919d8d53a48b3f8"),
    // output_note_get_recipient
    word!("0xc824115ed79a2e1670daed8c18fba1bc15f54c5ec0ec6699de69a00b21d9df92"),
    // output_note_add_asset
    word!("0x9b6929d1ce24b3a97c6fb098f2fa8d0958beb15f91e268b9c787194b0a977a0d"),
    // tx_get_num_input_notes
    word!("0xfcc186d4b65c584f3126dda1460b01eef977efd76f9e36f972554af28e33c685"),
    // tx_get_input_notes_commitment
    word!("0xc3a334434daa7d4ea15e1b2cb1a8000ad757f9348560a7246336662b77b0d89a"),
    // tx_get_num_output_notes
    word!("0x2511fca9c078cd96e526fd488d1362cbfd597eb3db8452aedb00beffee9782b4"),
    // tx_get_output_notes_commitment
    word!("0xd5b22dae48ec4b20ed479f2c43573d34930720886371ef6b484310a3bea4e818"),
    // tx_get_block_commitment
    word!("0xe474b491a64d222397fcf83ee5db7b048061988e5e83ce99b91bae6fd75a3522"),
    // tx_get_block_number
    word!("0x297797dff54b8108dd2df254b95d43895d3f917ab10399efc62adaf861c905ae"),
    // tx_get_block_timestamp
    word!("0x7903185b847517debb6c2072364e3e757b99ee623e97c2bd0a4661316c5c5418"),
    // tx_start_foreign_context
    word!("0xa53392b79f6caae70be66f33bc180dec56cabdb5d10481837bc44c7397d74bbb"),
    // tx_end_foreign_context
    word!("0xaa0018aa8da890b73511879487f65553753fb7df22de380dd84c11e6f77eec6f"),
    // tx_get_expiration_delta
    word!("0xa60286e820a755128b2269db5057b0e2d9b79fef6f813bf3fe3337553a8fbb53"),
    // tx_update_expiration_block_delta
    word!("0xa16440a9a8cd2a6d0ff7f5c3bcce2958976e5d3e6e8a6935ff40ae1863c324f0"),
];
