# Runs no-std related jobs.

name: no-std

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  no-std:
    name: build ${{matrix.toolchain}} no-std for wasm32-unknown-unknown
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - run: rustup target add wasm32-unknown-unknown
      - name: build-no-std
        run: make build-no-std
