name: Release-plz (next)

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - next

jobs:
  release-plz-dry-run-release:
    name: Release-plz release (dry-run)
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == '0xMiden' }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        config: .release-plz-dry-run.toml
        with:
          command: release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
