# Runs test related jobs.

name: test

# Limits workflow concurrency to only the latest commit in the PR.
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize] 

jobs:
  test:
    name: test ${{matrix.args}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        args: [default, prove]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
      - uses: taiki-e/install-action@nextest 
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/next' }}
      - name: Perform tests
        run: |
          rustup update --no-self-update 
          make test-${{matrix.args}}
