[package]
name = "miden-block-prover"
version = "0.8.0"
description = "Miden rollup block executor and prover"
readme = "README.md"
categories = ["no-std"]
keywords = ["miden", "block", "prover"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
bench = false

[features]
default = ["std"]
std = [
  "miden-objects/std",
  "miden-tx/std",
  "miden-crypto/std",
  "vm-core/std",
  "vm-processor/std",
]

[dependencies]
anyhow = { version = "1.0", default-features = false, optional = true }
miden-crypto = { workspace = true }
miden-tx = { workspace = true }
miden-objects = { workspace = true }
thiserror = { workspace = true }
vm-core = { workspace = true }
vm-processor = { workspace = true }

[dev-dependencies]
rand = { workspace = true, features = ["small_rng"] }
miden-lib = { workspace = true, features = ["std", "testing"] }
winterfell = { version = "0.11" }
anyhow = { version = "1.0", features = ["std", "backtrace"] }
miden-tx = { workspace = true, features = ["std", "testing"] }
