[package]
name = "miden_lib"
version = "0.1.0"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
keywords = ["miden", "program", "stdlib", "transaction", "kernel"]
edition = "2021"
rust-version = "1.65"

[lib]

[dependencies]
assembly = { package = "miden-assembly", git = "https://github.com/0xPolygonMiden/miden-vm" }
miden = { package = "miden-vm", git = "https://github.com/0xPolygonMiden/miden-vm" }
processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm" }

[dev-dependencies]
vm-core = { package = "miden-core", git = "https://github.com/0xPolygonMiden/miden-vm" }
miden = { package = "miden-vm", git = "https://github.com/0xPolygonMiden/miden-vm" , features = ["internals"]}

[build-dependencies]
assembly = { package = "miden-assembly", git = "https://github.com/0xPolygonMiden/miden-vm" }
miden = { package = "miden-vm", git = "https://github.com/0xPolygonMiden/miden-vm" }
processor = { package = "miden-processor", git = "https://github.com/0xPolygonMiden/miden-vm" }
