[package]
name = "miden-lib"
version = "0.1.0"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-base"
keywords = ["miden", "program", "stdlib", "transaction", "kernel"]
edition = "2021"
rust-version = "1.67"

[lib]

[features]
default = ["std"]
std = ["assembly/std", "vm-processor/std", "vm-core/std"]
testing = ["miden-objects/testing"]

[dependencies]
assembly = { workspace = true }
crypto = { workspace = true }
miden-objects = { package = "miden-objects", path = "../objects", default-features = false }
miden-stdlib = { workspace = true }
vm-core = { workspace = true }
vm-processor = { workspace = true }

[dev-dependencies]
miden-objects = { package = "miden-objects", path = "../objects", default-features = false, features = ["testing"] }
miden-stdlib = { workspace = true }
miden-tx = { package = "miden-tx", path = "../miden-tx", default-features = false }
mock = { package = "miden-mock", path = "../mock", default-features = false }
vm-processor = { workspace = true, features = ["internals"] }

[build-dependencies]
assembly = { workspace = true }
